export const product = [
    { id: 1, price: 10000, name: "Office chair", img: "productimage/oimg1.jpg", totalstocks: 30, category:"office" },
    { id: 2, price: 9000, name: "Gaming chair", img: "productimage/gimg1.jpg", totalstocks: 25, category:"gaming" },
    { id: 3, price: 12000, name: "Office chai", img: "productimage/oimg2.jpg", totalstocks: 40, category:"office" },
    { id: 4, price: 20000, name: "Office chair", img: "productimage/oimg3.jpg", totalstocks: 50, category:"office" },
    { id: 5, price: 2200, name: "Student chair", img: "productimage/stimg1.jpg", totalstocks: 40, category:"student" },
    { id: 6, price: 4500, name: "Cafe chair", img: "productimage/cfimg1.jpg", totalstocks: 10, category:"cafe" },
    { id: 7, price: 1200, name: "Office chair", img: "productimage/oimg4.jpg", totalstocks: 20, category:"office" },
    { id: 8, price: 3200, name: "Office chair", img: "productimage/oimg5.jpg", totalstocks: 50, category:"office" },
    { id: 9, price: 1300, name: "salon chair", img: "productimage/simg1.jpg", totalstocks: 10, category:"salon" },
    { id: 10, price: 13000, name: "Gaming chair", img: "productimage/gimg2.jpg", totalstocks: 30,category:"gaming" },
    { id: 11, price: 6000, name: "Student chair", img: "productimage/stimg2.jpg", totalstocks: 20,category:"student" },
    { id: 12, price: 8000, name: "Hotel chair", img: "productimage/himg1.jpg", totalstocks: 10,category:"hotel" },
    { id: 13, price: 14000, name: "Gaming chair", img: "productimage/gimg3.jpg", totalstocks: 9,category:"gaming" },
    { id: 14, price: 5000, name: "Student chair", img: "productimage/stimg3.jpg", totalstocks: 10,category:"student" },
     { id: 15, price: 8000, name: "Student chair", img: "productimage/stimg4.jpg", totalstocks: 30,category:"student" },
     { id: 16, price: 9000, name: "Gaming chair", img: "productimage/gimg4.jpg", totalstocks: 16,category:"gaming" },
     { id: 17, price: 11000, name: "Gaming chair", img: "productimage/gimg5.jpg", totalstocks: 10,category:"gaming" },
     { id: 18, price: 8500, name: "Cafe chair", img: "productimage/cfimg2.jpg", totalstocks: 10,category:"cafe" },
      { id: 19, price: 13000, name: "salon chair", img: "productimage/simg2.jpg", totalstocks: 5,category:"salon" },
      { id: 20, price: 2000, name: "Student chair", img: "productimage/stimg5.jpg", totalstocks: 12,category:"student" },
      { id: 21, price: 6000, name: "Student chair", img: "productimage/stimg6.jpg", totalstocks: 9,category:"student" },
      { id: 22, price: 3000, name: "Student chair", img: "productimage/stimg7.jpg", totalstocks: 10,category:"student" },
       { id: 23, price: 11000, name: "salon chair", img: "productimage/simg3.jpg", totalstocks: 5,category:"salon" },
        { id: 24, price: 1000, name: "Hotel chair", img: "productimage/himg2.jpg", totalstocks: 30,category:"hotel" },
        { id: 25, price: 3000, name: "Hotel chair", img: "productimage/himg3.jpg", totalstocks: 40,category:"hotel" },
        { id: 26, price: 2000, name: "Hotel chair", img: "productimage/himg4.jpg", totalstocks: 30,category:"hotel" },
        { id: 27, price: 9000, name: "Gaming chair", img: "productimage/gimg6.jpg", totalstocks: 10,category:"gaming" },
        { id: 28, price: 13000, name: "Gaming chair", img: "productimage/gimg7.jpg", totalstocks: 3,category:"gaming" },
        { id: 29, price: 10000, name: "Gaming chair", img: "productimage/gimg8.jpg", totalstocks: 10,category:"gaming" },
        { id: 30, price: 8000, name: "Gaming chair", img: "productimage/gimg9.jpg", totalstocks: 9,category:"gaming" },
];